[workspace]
channels = ["conda-forge"]
name = "poster-chtc-researcher-forum-2026"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
texlive-core = ">=20230313,<20230314"
qrcode = ">=8.2,<9"
